version: "3"
services:
  database:
    image: mysql:5.7
    networks:
      - events
    volumes:
      - events:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: events
      MYSQL_DATABASE: events
      MYSQL_USER: events
      MYSQL_PASSWORD: events
  events:
    image: jjino/event-notification
    depends_on:
      - database
    ports:
      - "80:4000"
    restart: always
    networks:
      - events
    environment:
      DB_HOST: database
      DB_USERNAME: events
      DB_PASSWORD: events
      DB_NAME: events
networks:
  events:
    driver: bridge
volumes:
  events: